### ISSUE TITLE
Looks like not working anymore.

### ISSUE THREAD

**Issue by Atahann17** [Eugenenoble2005/chesscheat#2]
Gives error like the game is not started. No more working.

**Comment by Eugenenoble2005** [comment]
Did you start it when you are in an active game?

**Comment by Atahann17** [comment]
> Did you start it when you are in an active game?

Yes, I did. I've been run it always in same way. Maybe chess.com fixed it?

![resim](https://github.com/Eugenenoble2005/chesscheat/assets/120344585/5ae0021a-df3e-4e6c-baa0-182ab2f000a0)

**Comment by Eugenenoble2005** [comment]
> > Did you start it when you are in an active game?
> 
> Yes, I did. I've been run it always in same way. Maybe chess.com fixed it?
> 
> ![resim](https://github.com/Eugenenoble2005/chesscheat/assets/120344585/5ae0021a-df3e-4e6c-baa0-182ab2f000a0)
> 

Hmmm, maybe chesscom patched it. I'll look into it.

**Comment by Eugenenoble2005** [comment]
Fixed,
